### ISSUE TITLE
[BUG] Counter Issues

### ISSUE THREAD

**Issue by ItsDrafty** [Larkinabout/fvtt-custom-dnd5e#27] opened 2024-02-26 23:07 UTC
Hi there,

I noticed as of the most recent update 0.7.2, counters are being wonky. Wasn't having issues before. It wasn't letting me add a maximum value for fractions and was just generally being weird. I can't really describe it any better and for my next issue will be obvious why. I can no longer edit counters as an option. I get this error in the console:

undry.js:753 TypeError: An error occurred while rendering CountersForm 474. key.split is not a function or its return value is not iterable
[Detected 1 package: custom-dnd5e]
    at Object.getProperty (commons.js:2536:24)
    at Localization.localize (foundry.js:7586:27)
    at Object.localize (foundry.js:7962:52)
    at Object.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:31:149)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at handlebars.min.js:27:7554
    at Array.forEach (<anonymous>)
    at handlebars.min.js:27:7522
    at Object.<anonymous> (handlebars.min.js:27:7597)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:11:49)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at Object.h (handlebars.min.js:27:18738)
    at Object.c [as invokePartial] (handlebars.min.js:27:15036)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:17:28)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at renderTemplate (foundry.js:7743:10)
    at async CountersForm._renderInner (foundry.js:5973:16)
    at async CountersForm._renderInner (foundry.js:6543:18)
    at async CountersForm.renderPatch (application-render.js:38:19)
    at async CountersForm._render (foundry.js:6532:5)

I am basically stuck with counters on the sheets that I can't configure. I can still click em to increase or decrease, but I can't access them in the module settings.

Any help would be appreciated, love the module.

Thanks,
Drafty

**Comment by Larkinabout** [comment] 2024-02-27 07:06
Hi Drafty,

Go into the Debug Settings and click to export the data to file and then attach the file here please, so I can investigate.

**Comment by Larkinabout** [comment] 2024-02-27 11:02
Update to 0.7.3 before you export the debug data as the previous version wasn't correctly including the settings data.

**Comment by Larkinabout** [comment] 2024-02-29 10:20
Closing as it looks like you resolved the issue separately and I cannot reproduce with the latest version.

**Closed by Larkinabout** 2024-02-29 10:20 UTC
Labels: bug
